// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxBrUrq7aoBhA475BKPU_i0VwBzAyVnaQ',
    appId: '1:147927430789:web:acf78404eb6a90711f9bec',
    messagingSenderId: '147927430789',
    projectId: 'ai-chat-app-4d8d1',
    authDomain: 'ai-chat-app-4d8d1.firebaseapp.com',
    storageBucket: 'ai-chat-app-4d8d1.firebasestorage.app',
    measurementId: 'G-61TPP8NYE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxBrUrq7aoBhA475BKPU_i0VwBzAyVnaQ',
    appId: '1:147927430789:web:acf78404eb6a90711f9bec', // Using web appId temporarily
    messagingSenderId: '147927430789',
    projectId: 'ai-chat-app-4d8d1',
    storageBucket: 'ai-chat-app-4d8d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxBrUrq7aoBhA475BKPU_i0VwBzAyVnaQ',
    appId: '1:147927430789:web:acf78404eb6a90711f9bec', // Using web appId temporarily
    messagingSenderId: '147927430789',
    projectId: 'ai-chat-app-4d8d1',
    storageBucket: 'ai-chat-app-4d8d1.firebasestorage.app',
    iosBundleId: 'com.example.cs310Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxBrUrq7aoBhA475BKPU_i0VwBzAyVnaQ',
    appId: '1:147927430789:web:acf78404eb6a90711f9bec', // Using web appId temporarily
    messagingSenderId: '147927430789',
    projectId: 'ai-chat-app-4d8d1',
    storageBucket: 'ai-chat-app-4d8d1.firebasestorage.app',
    iosBundleId: 'com.example.cs310Project',
  );
} 